details:
  namespace: bank-bookinfo-prd
  image: ghcr.io/bankhubjar/bookinfo-details
  tag: prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8082
  healthCheckPath: "/health"
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: bookinfo.hellodolphin.in.th
  path: "/bank/details(/|$)(.*)"
  # host: bookinfo.opsta.net
  # path: "/student108/details(/|$)(.*)"
  serviceType: ClusterIP
