reviews:
  namespace: bank-bookinfo-dev
  image: ghcr.io/bankhubjar/bookinfo-reviews
  tag: dev
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 9080
  healthCheckPath: "/health"
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: bookinfo.dev.hellodolphin.in.th
  path: "/bank/reviews(/|$)(.*)"
  # host: bookinfo.dev.opsta.net
  # path: "/student108/reviews(/|$)(.*)"
  serviceType: ClusterIP
extraEnv:
  RATINGS_SERVICE: "http://ratings:8081"
  SERVICE_VERSION: v1
  ENABLE_RATINGS: "true"
  STAR_COLOR: red